export const RIVERRACE_DATA = "RIVERRACE_DATA";
export const RIVERRACE_ERROR = "RIVERRACE_ERROR";
export const CURRENTRIVERRACE_DATA = "CURRENTRIVERRACE_DATA";
export const CURRENTRIVERRACE_ERROR = "CURRENTRIVERRACE_ERROR";
